### ISSUE TITLE
Transaction Failed When Transfering NFT Token

### ISSUE THREAD

**Issue by syedzahidulla** [tatumio/tatum-js#418]
I had created NFT MarketPlace With Tatum and minted token which were also seen in open sea testnet . when i tried to transfer the token with api call of tatum which uses safetransfer() it fails but when i transfered using opensea then it got transferd.

failing transaction id : 0xc5e11b38da10e50f4976de55a2b28ffb19a064cce03944518669009de06d1d5e

I tried through both rest api and tatum method ("transferNFT")

Still same result

**Comment by seanclarke** [comment]
Hi, chiming in since i'm seeing the same issue:

"Warning! Error encountered during contract execution [execution reverted]"

When transfering an NFT it seems like the Tatum endpoint ends up calling "safeTransfer  on the contract instead of "safeTransferFrom". Seems like it's treating the contract as ERC20 instead of ERC721.

Here's an example transaction that's failing, you can see from the "Input Data" that it's calling the "safeTransfer" method which does not exist on the contract:

https://polygonscan.com/tx/0xf2a72ec4fc9ecd9807b3d9a3d4640e7cdf3617ce1af6332cd7ea8208b5e03ed3

The decompiled contract where you can see it is indeed ERC721, lacking a "safeTransfer" method:

https://polygonscan.com/bytecode-decompiler?a=0x6a88646457beb1299c7fa9081027c1833735a7d4

Thank you for your help!
