### ISSUE TITLE
Which SDK to use?

### ISSUE THREAD

**Issue by pooyakn** [tatumio/tatum-js#785]
Hi,
I'm trying to create a virtual account using the Tatum SDK, but I'm confused about which version to use. Here are my questions:

- Which version of the Tatum SDK is recommended for creating virtual accounts?
- The [documentation](https://docs.tatum.io/guides/ledger-and-off-chain/how-to-use-ledger-accounts#create-a-virtual-account) shows examples using V1 SDK, but I'm not sure if this is still the best practice. Should I use V1, V2, or V3 (current master branch)?
- Why V3 doesn't seem to have any methods other than the notification API?
- If V2 is the best choice, can you provide guidance on how to create a virtual account using this version?
Thanks for your help!

Also, If Github is not suitable for asking such questions, please guide me to the right place. Thanks.

**Comment by Hathoriel** [comment]
Hi @pooyakn, 
Thank you for the question!
Right now we are improving V3 and yes - there is now only notifications support. More feature will be added in future in the V3 SDK.
The V2 SDK is suitable for you if you want to use full feature set what is Tatum offering. 
Here is the guide on [how to work with virtual accounts](https://docs.tatum.io/guides/ledger-and-off-chain).
The V1 SDK is outdated and instead of it I recommend you to should use V2 or V3 SDK. 
Hope this answer helps you.
